import { DbMovie } from 'src/app/core/store/omniflix.state.model';

export const SEED_MOVIES: DbMovie[] = [
  {
    id: '49181eb6-e1f0-4ab9-ab4a-f2cbd87e3591',
    title: 'Avengers: Endgame',
    released: new Date(2019, 3, 24).getTime(),
    runtime: 181,
    rating: 'PG-13',
    // tslint:disable-next-line: max-line-length
    summary: 'After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos\' actions and restore order to the universe once and for all, no matter what consequences may be in store.',
    budget: 356000000,
    revenue: 2797800564,
    tagline: 'Part of the journey is the end.',
    imdbRating: 8.5,
    generes: [],
    directors: [],
    writers: [],
    studios: [],
    tmdbId: 299534,
    imdbId: 'tt4154796',
    fanart: 'https://assets.fanart.tv/fanart/movies/299534/moviethumb/avengers-endgame-5c92e2929d176.jpg',
    fanartThumbnail: 'https://assets.fanart.tv/fanart/movies/299534/moviethumb/avengers-endgame-5c92e2929d176.jpg',
    poster: 'https://image.tmdb.org/t/p/w780/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg',
    posterThumbnail: 'https://image.tmdb.org/t/p/w185/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg',
    tmdbStatus: 'Released',
    updated: Date.now()
  },
  {
    id: '197361db-15ef-4a39-9273-12d81feedaa5',
    title: 'Once Upon a Time… in Hollywood',
    released: new Date(2019, 6, 25).getTime(),
    runtime: 162,
    rating: 'R',
    // tslint:disable-next-line: max-line-length
    summary: 'Los Angeles, 1969. TV star Rick Dalton, a struggling actor specializing in westerns, and stuntman Cliff Booth, his best friend, try to survive in a constantly changing movie industry. Dalton is the neighbor of the young and promising actress and model Sharon Tate, who has just married the prestigious Polish director Roman Polanski…',
    budget: 95000000,
    revenue: 371980270,
    tagline: 'In this town, it can all change… like that',
    imdbRating: 7.8,
    generes: [],
    directors: [],
    writers: [],
    studios: [],
    tmdbId: 466272,
    imdbId: 'tt7131622',
    fanart: 'https://fanart.tv/fanart/movies/466272/moviethumb/once-upon-a-time-in-hollywood-5dfeb7beb0d22.jpg',
    fanartThumbnail: 'https://fanart.tv/fanart/movies/466272/moviethumb/once-upon-a-time-in-hollywood-5dfeb7beb0d22.jpg',
    poster: 'https://image.tmdb.org/t/p/w780/oIpNs8TNPTDszf8YH9IFmXv8QKb.jpg',
    posterThumbnail: 'https://image.tmdb.org/t/p/w185/oIpNs8TNPTDszf8YH9IFmXv8QKb.jpg',
    tmdbStatus: 'Released',
    updated: Date.now()
  },
  {
    id: 'a7639dc8-2d4a-486d-a893-7aafe1f48937',
    title: 'Ford v Ferrari',
    released: new Date(2019, 10, 13).getTime(),
    runtime: 152,
    rating: 'PG-13',
    // tslint:disable-next-line: max-line-length
    summary: 'American car designer Carroll Shelby and the British-born driver Ken Miles work together to battle corporate interference, the laws of physics, and their own personal demons to build a revolutionary race car for Ford Motor Company and take on the dominating race cars of Enzo Ferrari at the 24 Hours of Le Mans in France in 1966.',
    budget: 97600000,
    revenue: 52437000,
    tagline: 'They took the American dream for a ride',
    imdbRating: 8.3,
    generes: [],
    directors: [],
    writers: [],
    studios: [],
    tmdbId: 359724,
    imdbId: 'tt1950186',
    fanart: 'https://assets.fanart.tv/fanart/movies/359724/moviethumb/ford-v-ferrari-5db749ff2a390.jpg',
    fanartThumbnail: 'https://assets.fanart.tv/fanart/movies/359724/moviethumb/ford-v-ferrari-5db749ff2a390.jpg',
    poster: 'https://image.tmdb.org/t/p/w780/xCIvjOKS6FvkxFIczinuX6VDWpr.jpg',
    posterThumbnail: 'https://image.tmdb.org/t/p/w185/xCIvjOKS6FvkxFIczinuX6VDWpr.jpg',
    tmdbStatus: 'Released',
    updated: Date.now()
  },
  {
    id: '4254a325-efe3-413b-8313-9145138595b7',
    title: 'Iron Man 2',
    released: new Date(2010, 3, 28).getTime(),
    runtime: 124,
    rating: 'PG-13',
    // tslint:disable-next-line: max-line-length
    summary: 'With the world now aware of his dual life as the armored superhero Iron Man, billionaire inventor Tony Stark faces pressure from the government, the press and the public to share his technology with the military. Unwilling to let go of his invention, Stark, with Pepper Potts and James \'Rhodey\' Rhodes at his side, must forge new alliances – and confront powerful enemies.',
    budget: 200000000,
    revenue: 623933331,
    tagline: 'It\'s not the armor that makes the hero, but the man inside.',
    imdbRating: 7,
    generes: [],
    directors: [],
    writers: [],
    studios: [],
    tmdbId: 10138,
    imdbId: 'tt1228705',
    fanart: 'https://assets.fanart.tv/fanart/movies/10138/moviethumb/iron-man-2-50452964a8ef0.jpg',
    fanartThumbnail: 'https://assets.fanart.tv/fanart/movies/10138/moviethumb/iron-man-2-50452964a8ef0.jpg',
    poster: 'https://assets.fanart.tv/fanart/movies/10138/movieposter/iron-man-2-5237fc247cc83.jpg',
    posterThumbnail: 'https://assets.fanart.tv/fanart/movies/10138/movieposter/iron-man-2-5237fc247cc83.jpg',
    tmdbStatus: 'Released',
    updated: Date.now()
  },
  {
    id: 'c19d08f7-0432-452c-b23a-e84210c9c845',
    title: 'Iron Man 3',
    released: new Date(2013, 3, 18).getTime(),
    runtime: 131,
    rating: 'PG-13',
    // tslint:disable-next-line: max-line-length
    summary: 'When Tony Stark\'s world is torn apart by a formidable terrorist called the Mandarin, he starts an odyssey of rebuilding and retribution.',
    budget: 200000000,
    revenue: 1215439994,
    tagline: 'Unleash the power behind the armor.',
    imdbRating: 7.2,
    generes: [],
    directors: [],
    writers: [],
    studios: [],
    tmdbId: 68721,
    imdbId: 'tt1300854',
    fanart: 'https://assets.fanart.tv/fanart/movies/68721/moviethumb/iron-man-3-52325c4f4ab49.jpg',
    fanartThumbnail: 'https://assets.fanart.tv/fanart/movies/68721/moviethumb/iron-man-3-52325c4f4ab49.jpg',
    poster: 'https://image.tmdb.org/t/p/w780/x6vjph1USM56MncpruT9jQP7xy2.jpg',
    posterThumbnail: 'https://image.tmdb.org/t/p/w185/x6vjph1USM56MncpruT9jQP7xy2.jpg',
    tmdbStatus: 'Released',
    updated: Date.now()
  },
  {
    id: '99a4458b-e8a0-4fea-b2d0-aa3c0ae7dc03',
    title: 'Ad Astra',
    released: new Date(2019, 8, 17).getTime(),
    runtime: 123,
    rating: 'PG-13',
    // tslint:disable-next-line: max-line-length
    summary: 'The near future, a time when both hope and hardships drive humanity to look to the stars and beyond. While a mysterious phenomenon menaces to destroy life on planet Earth, astronaut Roy McBride undertakes a mission across the immensity of space and its many perils to uncover the truth about a lost expedition that decades before boldly faced emptiness and silence in search of the unknown.',
    budget: 87500000,
    revenue: 127175902,
    tagline: 'The answers we seek are just outside our reach',
    imdbRating: 6.8,
    generes: [],
    directors: [],
    writers: [],
    studios: [],
    tmdbId: 419704,
    imdbId: 'tt2935510',
    fanart: 'https://fanart.tv/fanart/movies/419704/moviethumb/ad-astra-5de73c8b67995.jpg',
    fanartThumbnail: 'https://fanart.tv/fanart/movies/419704/moviethumb/ad-astra-5de73c8b67995.jpg',
    poster: 'https://image.tmdb.org/t/p/w780/xBHvZcjRiWyobQ9kxBhO6B2dtRI.jpg',
    posterThumbnail: 'https://image.tmdb.org/t/p/w185/xBHvZcjRiWyobQ9kxBhO6B2dtRI.jpg',
    tmdbStatus: 'Released',
    updated: Date.now()
  },
  {
    id: 'bf67d889-a3cb-48b0-96e7-12b59bf01c56',
    title: 'The Irishman',
    released: new Date(2019, 10, 1).getTime(),
    runtime: 209,
    rating: 'R',
    // tslint:disable-next-line: max-line-length
    summary: 'Pennsylvania, 1956. Frank Sheeran, a war veteran of Irish origin who works as a truck driver, accidentally meets mobster Russell Bufalino. Once Frank becomes his trusted man, Bufalino sends him to Chicago with the task of helping Jimmy Hoffa, a powerful union leader related to organized crime, with whom Frank will maintain a close friendship for nearly twenty years.',
    budget: 159000000,
    revenue: 607420,
    tagline: 'His story changed history',
    imdbRating: 8.2,
    generes: [],
    directors: [],
    writers: [],
    studios: [],
    tmdbId: 398978,
    imdbId: 'tt1302006',
    fanart: 'https://assets.fanart.tv/fanart/movies/398978/moviethumb/the-irishman-5db9cb2279764.jpg',
    fanartThumbnail: 'https://assets.fanart.tv/fanart/movies/398978/moviethumb/the-irishman-5db9cb2279764.jpg',
    poster: 'https://image.tmdb.org/t/p/w780/xOJKDKlb7kVvZfT9RPt0hwlwEqL.jpg',
    posterThumbnail: 'https://image.tmdb.org/t/p/w185/xOJKDKlb7kVvZfT9RPt0hwlwEqL.jpg',
    tmdbStatus: 'Released',
    updated: Date.now()
  },
  {
    id: '0abb45be-8627-4fab-88e2-cbc926e75721',
    title: 'Ready Player One',
    released: new Date(2018, 2, 28).getTime(),
    runtime: 140,
    rating: 'PG-13',
    // tslint:disable-next-line: max-line-length
    summary: 'When the creator of a popular video game system dies, a virtual contest is created to compete for his fortune.',
    budget: 175000000,
    revenue: 582890172,
    tagline: 'A better reality awaits.',
    imdbRating: 7.5,
    generes: [],
    directors: [],
    writers: [],
    studios: [],
    tmdbId: 333339,
    imdbId: 'tt1677720',
    fanart: 'https://assets.fanart.tv/fanart/movies/333339/moviethumb/ready-player-one-5dfec9739d4aa.jpg',
    fanartThumbnail: 'https://assets.fanart.tv/fanart/movies/333339/moviethumb/ready-player-one-5dfec9739d4aa.jpg',
    poster: 'https://image.tmdb.org/t/p/w780/n99BOeaRjwU9rvnwQfzfwBIvx48.jpg',
    posterThumbnail: 'https://image.tmdb.org/t/p/w185/n99BOeaRjwU9rvnwQfzfwBIvx48.jpg',
    tmdbStatus: 'Released',
    updated: Date.now()
  },
  {
    id: 'e0068020-fee1-4cad-b386-a3ac180f5a72',
    title: 'Rambo: Last Blood',
    released: new Date(2019, 8, 19).getTime(),
    runtime: 89,
    rating: 'R',
    // tslint:disable-next-line: max-line-length
    summary: 'After fighting his demons for decades, John Rambo now lives in peace on his family ranch in Arizona, but his rest is interrupted when Gabriela, the granddaughter of his housekeeper María, disappears after crossing the border into Mexico to meet her biological father. Rambo, who has become a true father figure for Gabriela over the years, undertakes a desperate and dangerous journey to find her.',
    budget: 50000000,
    revenue: 87041796,
    tagline: 'Everyone has one more fight in them',
    imdbRating: 6.3,
    generes: [],
    directors: [],
    writers: [],
    studios: [],
    tmdbId: 522938,
    imdbId: 'tt1206885',
    fanart: '/assets/fanarts/e0068020-fee1-4cad-b386-a3ac180f5a72.jpg',
    fanartThumbnail: '/assets/fanarts/e0068020-fee1-4cad-b386-a3ac180f5a72.jpg',
    poster: 'https://image.tmdb.org/t/p/w780/kTQ3J8oTTKofAVLYnds2cHUz9KO.jpg',
    posterThumbnail: 'https://image.tmdb.org/t/p/w185/kTQ3J8oTTKofAVLYnds2cHUz9KO.jpg',
    tmdbStatus: 'Released',
    updated: Date.now()
  },
  {
    id: '15fb8762-2b8e-4954-9d4f-0c7e3b75c448',
    title: 'It Chapter Two',
    released: new Date(2019, 8, 4).getTime(),
    runtime: 169,
    rating: 'R',
    // tslint:disable-next-line: max-line-length
    summary: '27 years after overcoming the malevolent supernatural entity Pennywise, the former members of the Losers\' Club, who have grown up and moved away from Derry, are brought back together by a devastating phone call.',
    budget: 79000000,
    revenue: 472093228,
    tagline: 'You\'ll Float Again',
    imdbRating: 6.7,
    generes: [],
    directors: [],
    writers: [],
    studios: [],
    tmdbId: 474350,
    imdbId: 'tt7349950',
    fanart: 'https://assets.fanart.tv/fanart/movies/474350/moviethumb/it-chapter-2-5d9cdd9141a3a.jpg',
    fanartThumbnail: 'https://assets.fanart.tv/fanart/movies/474350/moviethumb/it-chapter-2-5d9cdd9141a3a.jpg',
    poster: 'https://image.tmdb.org/t/p/w780/wF6SNPcUrTKFA4fOFfukm7zQ3ob.jpg',
    posterThumbnail: 'https://image.tmdb.org/t/p/w185/wF6SNPcUrTKFA4fOFfukm7zQ3ob.jpg',
    tmdbStatus: 'Released',
    updated: Date.now()
  },
  {
    id: '9e9b0cdf-b1ac-4e44-8eb1-f2fe8237290a',
    title: 'Angel Has Fallen',
    released: new Date(2019, 8, 21).getTime(),
    runtime: 122,
    rating: 'R',
    // tslint:disable-next-line: max-line-length
    summary: 'After a treacherous attack, Secret Service agent Mike Banning is charged with attempting to assassinate President Trumbull. Chased by his own colleagues and the FBI, Banning begins a race against the clock to clear his name.',
    budget: 40000000,
    revenue: 133365452,
    tagline: 'Loyalty is under fire',
    imdbRating: 6.4,
    generes: [],
    directors: [],
    writers: [],
    studios: [],
    tmdbId: 423204,
    imdbId: 'tt6189022',
    fanart: 'https://assets.fanart.tv/fanart/movies/423204/moviethumb/angel-has-fallen-5dfec9b3a4001.jpg',
    fanartThumbnail: 'https://assets.fanart.tv/fanart/movies/423204/moviethumb/angel-has-fallen-5dfec9b3a4001.jpg',
    poster: 'https://image.tmdb.org/t/p/w780/fapXd3v9qTcNBTm39ZC4KUVQDNf.jpg',
    posterThumbnail: 'https://image.tmdb.org/t/p/w185/fapXd3v9qTcNBTm39ZC4KUVQDNf.jpg',
    tmdbStatus: 'Released',
    updated: Date.now()
  },
  {
    id: 'd5f5f2ea-8aa8-4bf9-935a-3e3fa6bb3c47',
    title: 'Abominable',
    released: new Date(2019, 8, 19).getTime(),
    runtime: 92,
    rating: 'PG',
    // tslint:disable-next-line: max-line-length
    summary: 'A group of misfits encounter a young Yeti named Everest, and they set off to reunite the magical creature with his family on the mountain of his namesake.',
    budget: 75000000,
    revenue: 111615070,
    tagline: '',
    imdbRating: 7,
    generes: [],
    directors: [],
    writers: [],
    studios: [],
    tmdbId: 431580,
    imdbId: 'tt6324278',
    fanart: 'https://fanart.tv/fanart/movies/431580/moviethumb/abominable-5de12b8b20595.jpg',
    fanartThumbnail: 'https://fanart.tv/fanart/movies/431580/moviethumb/abominable-5de12b8b20595.jpg',
    poster: 'https://image.tmdb.org/t/p/w780/hfztes4fniYO3HSnbLlEdCr6Sgf.jpg',
    posterThumbnail: 'https://image.tmdb.org/t/p/w185/hfztes4fniYO3HSnbLlEdCr6Sgf.jpg',
    tmdbStatus: 'Released',
    updated: Date.now()
  },
  {
    id: '1f017a06-36d9-4ea0-a2a6-5d741d028500',
    title: 'Joker',
    released: new Date(2019, 9, 2).getTime(),
    runtime: 122,
    rating: 'R',
    // tslint:disable-next-line: max-line-length
    summary: 'During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic crime figure.',
    budget: 55000000,
    revenue: 1059735374,
    tagline: 'Put on a happy face.',
    imdbRating: 8.7,
    generes: [],
    directors: [],
    writers: [],
    studios: [],
    tmdbId: 475557,
    imdbId: 'tt7286456',
    fanart: 'https://assets.fanart.tv/fanart/movies/475557/moviethumb/joker-5d6fffc09bb06.jpg',
    fanartThumbnail: 'https://assets.fanart.tv/fanart/movies/475557/moviethumb/joker-5d6fffc09bb06.jpg',
    poster: 'https://image.tmdb.org/t/p/w780/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg',
    posterThumbnail: 'https://image.tmdb.org/t/p/w185/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg',
    tmdbStatus: 'Released',
    updated: Date.now()
  },
  {
    id: '907a2141-2558-4331-bb01-f0f2188fe87e',
    title: 'Gemini Man',
    released: new Date(2019, 9, 2).getTime(),
    runtime: 117,
    rating: 'PG-13',
    // tslint:disable-next-line: max-line-length
    summary: 'Ageing assassin, Henry Brogen tries to get out of the business but finds himself in the ultimate battle—fighting his own clone who is 25 years younger than him, and at the peak of his abilities.',
    budget: 138000000,
    revenue: 59552372,
    tagline: 'Who will save you from yourself?',
    imdbRating: 5.7,
    generes: [],
    directors: [],
    writers: [],
    studios: [],
    tmdbId: 453405,
    imdbId: 'tt1025100',
    fanart: 'https://fanart.tv/fanart/movies/453405/moviethumb/gemini-man-5da9582a1b0b8.jpg',
    fanartThumbnail: 'https://fanart.tv/fanart/movies/453405/moviethumb/gemini-man-5da9582a1b0b8.jpg',
    poster: 'https://image.tmdb.org/t/p/w780/fH7onSvyeC6NnHND0Hh2sLpRMi7.jpg',
    posterThumbnail: 'https://image.tmdb.org/t/p/w185/fH7onSvyeC6NnHND0Hh2sLpRMi7.jpg',
    tmdbStatus: 'Released',
    updated: Date.now()
  },
  {
    id: '55c02722-f41b-4005-b6f4-b5d7982152e3',
    title: 'Shazam!',
    released: new Date(2019, 2, 23).getTime(),
    runtime: 132,
    rating: 'PG-13',
    // tslint:disable-next-line: max-line-length
    summary: 'A boy is given the ability to become an adult superhero in times of need with a single magic word.',
    budget: 80000000,
    revenue: 363533271,
    tagline: 'Just Say The Word',
    imdbRating: 7.1,
    generes: [],
    directors: [],
    writers: [],
    studios: [],
    tmdbId: 287947,
    imdbId: 'tt0448115',
    fanart: 'https://assets.fanart.tv/fanart/movies/287947/moviethumb/shazam-5c7d9c528f88a.jpg',
    fanartThumbnail: 'https://assets.fanart.tv/fanart/movies/287947/moviethumb/shazam-5c7d9c528f88a.jpg',
    poster: 'https://image.tmdb.org/t/p/w780/xnopI5Xtky18MPhK40cZAGAOVeV.jpg',
    posterThumbnail: 'https://image.tmdb.org/t/p/w185/xnopI5Xtky18MPhK40cZAGAOVeV.jpg',
    tmdbStatus: 'Released',
    updated: Date.now()
  },
  {
    id: '5288c5d4-2669-4dee-8bcc-2ce9038d1759',
    title: 'Fast & Furious Presents: Hobbs & Shaw',
    released: new Date(2019, 7, 1).getTime(),
    runtime: 137,
    rating: 'PG-13',
    // tslint:disable-next-line: max-line-length
    summary: 'Ever since US Diplomatic Security Service Agent Hobbs and lawless outcast Shaw first faced off, they just have swapped smacks and bad words. But when cyber-genetically enhanced anarchist Brixton\'s ruthless actions threaten the future of humanity, both join forces to defeat him. (A spin-off of “The Fate of the Furious,” focusing on Johnson\'s Luke Hobbs and Statham\'s Deckard Shaw.)',
    budget: 200000000,
    revenue: 760098996,
    tagline: '',
    imdbRating: 6.5,
    generes: [],
    directors: [],
    writers: [],
    studios: [],
    tmdbId: 384018,
    imdbId: 'tt6806448',
    fanart: 'https://assets.fanart.tv/fanart/movies/384018/moviethumb/fast--furious-presents-hobbs--shaw-5dfecb9e08cf1.jpg',
    fanartThumbnail: 'https://assets.fanart.tv/fanart/movies/384018/moviethumb/fast--furious-presents-hobbs--shaw-5dfecb9e08cf1.jpg',
    poster: 'https://image.tmdb.org/t/p/w780/8XcYJsmT0qHZNyMrv258xDICNWk.jpg',
    posterThumbnail: 'https://image.tmdb.org/t/p/w185/8XcYJsmT0qHZNyMrv258xDICNWk.jpg',
    tmdbStatus: 'Released',
    updated: Date.now()
  },
  {
    id: 'df5a7bd3-8112-4426-b838-4a5122d54c56',
    title: 'Ready or Not',
    released: new Date(2019, 7, 21).getTime(),
    runtime: 95,
    rating: 'R',
    // tslint:disable-next-line: max-line-length
    summary: 'A bride\'s wedding night takes a sinister turn when her eccentric new in-laws force her to take part in a terrifying game.',
    budget: 6000000,
    revenue: 57384179,
    tagline: 'In-Laws Can Be Murder',
    imdbRating: 6.9,
    generes: [],
    directors: [],
    writers: [],
    studios: [],
    tmdbId: 567609,
    imdbId: 'tt7798634',
    fanart: 'https://assets.fanart.tv/fanart/movies/567609/moviethumb/ready-or-not-5de20f68e0d20.jpg',
    fanartThumbnail: 'https://assets.fanart.tv/fanart/movies/567609/moviethumb/ready-or-not-5de20f68e0d20.jpg',
    poster: 'https://image.tmdb.org/t/p/w780/fwTgNM1PiBYO1J86ZZ1nCKivRFl.jpg',
    posterThumbnail: 'https://image.tmdb.org/t/p/w185/fwTgNM1PiBYO1J86ZZ1nCKivRFl.jpg',
    tmdbStatus: 'Released',
    updated: Date.now()
  }
];
